make blue look vintage & line nr color & bash prompt changes

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -20,6 +20,40 @@ export FZF_COMPLETION_OPTS='--select-1'
 export FZF_DEFAULT_OPTS='--color=16 --inline-info'
 export FZF_CTRL_T_OPTS='--select-1'
 
+############################################################
+##########  prompt  ########################################
+############################################################
+
+prompt_command() {
+  # store last return code, as subsequent commands will overwrite it.
+  RETC="$?"
+
+  # store nix-shell status to display later, if nonempty
+  # (displays derivation name if exported as $NIX_SHELL_NAME)
+  if [[ $IN_NIX_SHELL != "" ]]; then
+    [[ $NIX_SHELL_NAME != "" ]] && NS=" $NIX_SHELL_NAME " || NS=" $IN_NIX_SHELL "
+  else
+    NS=' '
+  fi
+
+  # prompt showing the user, hostname, cwd, and return codes.
+  PS1="\[\e[90m\u@\h \e[1m\e[32m\w\e[36m$NS\e[39m$RETC\[\e[m\] "
+
+  # append each line to history individually.
+  history -a
+}
+
+PROMPT_DIRTRIM=3
+PROMPT_COMMAND=prompt_command
+
+# patches for ls coloring
+# https://geoff.greer.fm/lscolors/
+export CLICOLOR=1
+export LSCOLORS=ExDxDxDxCxDxDxCxCxExEx
+LS_COLORS="di=1;34:ln=1;33:so=1;33:pi=1;33:ex=1;32:bd=1;"
+LS_COLORS+="33:cd=1;33:su=1;32:sg=1;32:tw=1;34:ow=1;34"
+export LS_COLORS
+
 #%%%%%%%%%%%%%%%%%%
 #%%% Functions %%%%
 #%%%%%%%%%%%%%%%%%%
@@ -82,8 +116,3 @@ alias ta='tmux attach -t '
 alias td='tmux detach'
 alias tn='tmux new -s'
 alias tk='tmux kill-session -t'
-
-#%%%%%%%%%%%%%%%%%%%
-#%%%%  Colors  %%%%%
-#%%%%%%%%%%%%%%%%%%%
-
